### ISSUE TITLE
Host docs on readthedocs

### ISSUE THREAD

**Issue by 0x1mason** [appium/droiddriver#21]
I haven't used it before, but always impressed by sites that use it. Nicer than the default JavaDoc theme, anyway.  https://readthedocs.org/

**Comment by bootstraponline** [comment]
does it support java/javadoc?

**Comment by 0x1mason** [comment]
Looks like it
http://approval.readthedocs.org/en/latest/javadoc/packages.html

**Comment by bootstraponline** [comment]
I think the standard [javadoc](http://appium.github.io/droiddriver/javadoc/) is more usable. we could try it though.

**Comment by 0x1mason** [comment]
Sounds good.  Not married to the idea.

**Comment by bootstraponline** [comment]
http://droiddriver.readthedocs.org/en/latest/contributing/

It looks like javadocs aren't supported. We'd need to use [a special binary](https://github.com/nikolavp/approval/commit/8fa629aea5148ad68cbb2809044f80c290ccb0c2#diff-555c472a89566734e0d8567fb205d5dfR20) to generate them in the appropriate format.

**Comment by 0x1mason** [comment]
Alright.  We can decide later if it's worth it.

**Comment by bootstraponline** [comment]
I think this would be cool for appium since all those docs are in an already supported format (markdown). To use this on droiddriver:

- We'd have to install `javasphinx-apidoc` on the jenkins build machines (it has no integration with gradle from what I can tell so running locally would be painful)
- Auto trigger the doc generation on each commit using a github webhook
- Publish docs to a sphinx branch which readthedocs.org uses to generate the html pages

Unless a few java devs chime in that there's some advantage to sphinx, I'm thinking our efforts are best directed elsewhere for now.

**Comment by bootstraponline** [comment]
Oh. It doesn't even work on the appium repo.

- https://readthedocs.org/builds/appium/2321702/
