### ISSUE TITLE
code coverage

### ISSUE THREAD

**Issue by bootstraponline** [appium/droiddriver#28]
It'd be nice to document/have an example of using jacoco with droiddriver to generate code coverage numbers.

- https://github.com/nenick/android-gradle-template/

**Comment by ddkjin** [comment]
This is an interesting topic. A common practice at Google is that we exclude large tests (including UI tests) for coverage measurement because they give pleasant but misleading numbers.
In general, line coverage should only count unit tests. The coverage of UI tests should be measured as the ratio of automated use cases, instead of lines.

**Comment by bootstraponline** [comment]
You're correct. I'd still rather have the data though. In my experience with appium, it's common for companies to collect metrics from their UI tests even if they're not representative of much.

Last year I used [ant/emma](https://github.com/appium/appium/blob/b163180a54dd25c3f626aed59dee02a55c901328/docs/en/android_coverage.md) to generate code coverage. That's now been replaced with gradle/jacoco. It looks like jacoco has a gradle plugin so the integration appears to be simple.

**Comment by bootstraponline** [comment]
Looks like coverage is a one line change.

- https://github.com/appium/droiddriver_examples/commit/931d6b0c84c3cb85120c3308598a4548044d065c
